### ISSUE TITLE
gambler award

### ISSUE THREAD

**Issue by grimreapershousewife** [mwoiii/stat-mod-ror2#4]
add points towards a counter whenever someone uses a shrine of order or a lunar cauldron without the required amount of scrap (e.g. red cauldron when only having 3 green scrap + 1 regen scrap)

use "inventory.GetItemCount(RoR2Content.Items.ScrapWhite);" to address individual items

**Comment by mwoiii** [comment]
Shrine of Order counter complete, but still working on scrappers/cauldrons because unfortunately they are not simple to work with

**Comment by mwoiii** [comment]
Alas I have done it
