### ISSUE TITLE
chef award

### ISSUE THREAD

**Issue by nod03** [mwoiii/stat-mod-ror2#6]
track the increments of the vanilla statistics damage dealt, kills on each stage, and number of each item held. Identify stagnant increases followed by a significant increase, indicating that a player has completed a build/item synergy, etc., and evaluating how successful it was. Other stats such as item scrapping and printing incrementers could be implemented and tracked to solidify the identification of this behaviour.

public methods to recieve the vanilla stats in different data types can be found in the instance of RoR2.Stats.StatSheet

**Comment by mwoiii** [comment]
All/sufficient relevant stats exist to identify behaviour, just need to implement awards themselves
